package id.homebase.chat.services.convo

import id.homebase.api.client.KeyHeader
import id.homebase.api.client.auth.CredentialsManager
import id.homebase.api.client.drives.HomebaseFile
import id.homebase.api.client.drives.QueryBatchSortField
import id.homebase.api.client.drives.QueryBatchSortOrder
import id.homebase.api.client.drives.upload.DriveUploadProvider
import id.homebase.api.client.drives.upload.FileUpdateInstructionSet
import id.homebase.api.client.drives.upload.TransitOptions
import id.homebase.api.client.drives.upload.UpdateFileByUniqueIdRequest
import id.homebase.api.client.drives.upload.UpdateLocale
import id.homebase.api.client.drives.upload.UpdateManifest
import id.homebase.api.client.drives.upload.UploadAppFileMetaData
import id.homebase.api.client.drives.upload.UploadFileMetadata
import id.homebase.api.client.drives.upload.UploadFileRequest
import id.homebase.api.common.OdinId
import id.homebase.api.common.time.UnixTimeUtc
import id.homebase.api.crypto.ByteArrayUtil
import id.homebase.api.serialization.OdinSystemSerializer
import id.homebase.api.sync.database.DatabaseManager
import id.homebase.api.sync.database.QueryBatch
import id.homebase.chat.data.ConversationUiModel
import id.homebase.chat.services.ChatMessageStream
import id.homebase.chat.services.ChatProtocol
import id.homebase.chat.services.PayloadBundle
import id.homebase.chat.services.PayloadBundleEncryptionService
import id.homebase.chat.services.XorIdUtil
import id.homebase.core.avatars.ConversationAvatarModel
import id.homebase.core.config.chatTargetDrive
import id.homebase.core.image.HomebaseImageData
import id.homebase.core.image.ImageSize
import kotlinx.coroutines.CoroutineScope
import kotlin.io.encoding.Base64
import kotlin.uuid.Uuid


class ConversationService(
    private val credentialsManager: CredentialsManager,
    private val driveUploadProvider: DriveUploadProvider,
    private val payloadBundleEncryptionService: PayloadBundleEncryptionService,
    private val dbm: DatabaseManager,
    private val contactService: ContactService,
    private val scope: CoroutineScope
) {
    private val chatDrive = chatTargetDrive.alias

    suspend fun createConversation(
        recipients: List<OdinId>,
        title: String?,
        payloadBundle: PayloadBundle?
    ): Uuid {

        val credentials = credentialsManager.requireActiveCredentials()
        val domain = credentials.domain
        val keyHeader = KeyHeader.newRandom16()

        val newConversationId: Uuid =
            if (recipients.size == 1) {
                XorIdUtil.getNewXorId(domain.domainName, recipients.first().domainName)
            } else {
                Uuid.random()
            }


        val existingConversation = getConversation(newConversationId)
        if (existingConversation != null) {
            return newConversationId
        }

        val content = ConversationAppDataJson(
            title = title ?: "",
            recipients = (recipients + domain).distinct(),
            version = 1
        )

        val encryptedBundle = payloadBundleEncryptionService
            .encryptBundle(newConversationId, payloadBundle, keyHeader.aesKey, scope)

        val metadata =
            UploadFileMetadata(
                allowDistribution = true,
                isEncrypted = true,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = newConversationId.toString(),
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail = encryptedBundle
                            .previewThumbs
                            .minByOrNull { it.pixelWidth }  //TODO:need to get the embeded thum generated by the thumbnail creator
                    ),
            )

        val request =
            UploadFileRequest(
                driveId = chatDrive,
                keyHeader = keyHeader,
                metadata = metadata.encryptContent(keyHeader),
                transitOptions =
                    TransitOptions(
                        recipients = recipients,
                        useAppNotification = false
                    ),
                payloads = encryptedBundle.payloads,
                thumbnails = encryptedBundle.thumbnails
            )

        driveUploadProvider.uploadFile(request)
        return newConversationId
    }

    suspend fun requireConversation(conversationId: Uuid): ConversationUiModel {
        return getConversation(conversationId)
            ?: throw IllegalStateException("No conversation for Id")
    }

    suspend fun getConversation(
        conversationId: Uuid
    ): ConversationUiModel? {
        val file = getConversationHomebaseFile(conversationId) ?: return null
        return mapToConversationUi(file, null)
    }

    suspend fun updateConversationRecipients(
        conversationId: Uuid,
        recipients: List<OdinId>
    ) {
        val conversationFile = getConversationHomebaseFile(conversationId)
            ?: error("No conversation found")

        val credentials = credentialsManager.requireActiveCredentials()
        val domain = credentials.domain

        val normalizedRecipients = (recipients + domain).distinct()

        val keyHeader = KeyHeader.newRandom16()

        val existingAppData = OdinSystemSerializer.deserialize<ConversationAppDataJson>(
            conversationFile.fileMetadata.appData.content ?: ""
        )
        val content =
            ConversationAppDataJson(
                title = existingAppData.title,
                recipients = normalizedRecipients,
                version = existingAppData.version
            )

        val manifest =
            UpdateManifest.build(
                payloads = null,
                toDeletePayloads = null,
                thumbnails = null,
                generatePayloadIv = false
            )

        val metadata =
            UploadFileMetadata(
                allowDistribution = true, //todo: base on transfer history as optimization
                isEncrypted = true,
                versionTag = conversationFile.fileMetadata.versionTag,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = conversationId.toString(),
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail = conversationFile.fileMetadata.appData.previewThumbnail
                    )
            )

        val instructions =
            FileUpdateInstructionSet(
                transferIv = ByteArrayUtil.getRndByteArray(16),
                locale = UpdateLocale.Local,
                recipients = recipients,
                manifest = manifest
            )

        val request =
            UpdateFileByUniqueIdRequest(
                driveId = chatDrive,
                uniqueId = conversationId,
                keyHeader = keyHeader,
                instructions = instructions,
                metadata = metadata.encryptContent(keyHeader),
                payloads = null,
                thumbnails = null
            )

        driveUploadProvider.updateFileByUniqueId(
            request = request,
            onVersionConflict = {
                // caller decides retry strategy; surface conflict cleanly
                null
            }
        )
    }

    suspend fun updateConversation(
        conversationId: Uuid,
        title: String?,
        recipients: List<OdinId>,
        payloadBundle: PayloadBundle
    ) {
        val credentials = credentialsManager.requireActiveCredentials()
        val domain = credentials.domain

        val conversationFile = getConversationHomebaseFile(conversationId)
            ?: error("No conversation found")

        // Always include self, never distribute to self
        val normalizedRecipients = (recipients + domain).distinct()

        val keyHeader = KeyHeader.newRandom16()

        val content =
            ConversationAppDataJson(
                title = title ?: "",
                recipients = normalizedRecipients,
                version = 1 // logical version; server enforces via versionTag
            )

        val encryptedBundle = payloadBundleEncryptionService
            .encryptBundle(conversationId, payloadBundle, keyHeader.aesKey, scope)

        val manifest =
            UpdateManifest.build(
                payloads = encryptedBundle.payloads,
                toDeletePayloads = null,
                thumbnails = encryptedBundle.thumbnails,
                generatePayloadIv = false
            )

        val metadata =
            UploadFileMetadata(
                allowDistribution = true, //todo: base on transfer history as optimization
                isEncrypted = true,
                versionTag = conversationFile.fileMetadata.versionTag,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = conversationId.toString(),
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail =
                            encryptedBundle.previewThumbs.minByOrNull { it.pixelWidth }
                    )
            )

        val instructions =
            FileUpdateInstructionSet(
                transferIv = ByteArrayUtil.getRndByteArray(16),
                locale = UpdateLocale.Local,
                recipients = recipients,
                manifest = manifest
            )

        val request =
            UpdateFileByUniqueIdRequest(
                driveId = chatDrive,
                uniqueId = conversationId,
                keyHeader = keyHeader,
                instructions = instructions,
                metadata = metadata.encryptContent(keyHeader),
                payloads = encryptedBundle.payloads,
                thumbnails = encryptedBundle.thumbnails
            )

        driveUploadProvider.updateFileByUniqueId(
            request = request,
            onVersionConflict = {
                // caller decides retry strategy; surface conflict cleanly
                null
            }
        )
    }

    private suspend fun getConversationHomebaseFile(conversationId: Uuid): HomebaseFile? {

        val c = credentialsManager.requireActiveCredentials()
        val queryBatch = QueryBatch(c.getIdentityId())

        val result =
            queryBatch.queryBatchAsync(
                dbm = dbm,
                driveId = chatDrive,
                noOfItems = 1,
                cursor = null,
                sortOrder = QueryBatchSortOrder.NewestFirst,
                sortField = QueryBatchSortField.CreatedDate,
                fileSystemType = 0,
                uniqueIdAnyOf = listOf(conversationId),
                filetypesAnyOf = listOf(ChatProtocol.ConversationFileType),
            )

        val file = result.records.firstOrNull()
        return file
    }

    suspend fun mapToConversationUi(
        conversation: HomebaseFile,
        lastMsg: HomebaseFile?
    ): ConversationUiModel {

        val metadata = conversation.fileMetadata
        val appData = metadata.appData

        if (appData.fileType != ChatProtocol.ConversationFileType) {
            throw IllegalArgumentException("Not a conversation file")
        }

        val appDataObj =
            OdinSystemSerializer.deserialize<ConversationAppDataJson>(
                appData.content ?: error("Conversation appData missing")
            )

        val domain = credentialsManager.getActiveDomain()
            ?: error("No active domain")

        val localAppData =
            metadata.localAppData?.content?.let {
                OdinSystemSerializer.deserialize<ConversationLocalAppDataJson>(it)
            }

        val participants = appDataObj.recipients

        val displayNames =
            participants.map { odinId ->
                contactService.resolveByOdinId(odinId)?.name
                    ?: odinId.domainName
            }

        val title =
            if (participants.size == 2) {
                val other = participants.first { it != domain }
                contactService.resolveByOdinId(other)?.name
                    ?: "fracko"

            } else {
                appDataObj.title ?: displayNames.joinToString(", ")
            }

        // -------- avatar initials selection (no derivation) --------

        val avatarModel = buildConversationAvatarModel(conversation)

        val ui =
            ConversationUiModel(
                id = appData.uniqueId ?: error("Missing uniqueId"),
                name = title,
                lastMessage = " ",
                timestamp = UnixTimeUtc(0).toInstant(),
                unreadCount = 0,
                avatarTiny = appData.previewThumbnail,
                avatarInitials = "",
                avatarUrl = "",
                participants = participants,
                lastRead =
                    localAppData?.lastReadTime?.toInstant()
                        ?: UnixTimeUtc(0).toInstant(),
                avatarModel = avatarModel
            )

        if (lastMsg != null) {
            ChatMessageStream
                .mapToMessageData(lastMsg, ::resolveDisplayName)
                ?.let { ui.updateWithLatestMessage(it) }
        }

        return ui
    }

    private suspend fun resolveDisplayName(file: HomebaseFile): String {
        val author = file.fileMetadata.originalAuthor ?: return ""

        return contactService
            .resolveByOdinId(author)
            ?.name
            ?: author.domainName
    }

    private suspend fun buildConversationAvatarModel(
        conversation: HomebaseFile
    ): ConversationAvatarModel {

        val metadata = conversation.fileMetadata
        val appData = metadata.appData

        val domain = credentialsManager.getActiveDomain()
            ?: error("No active domain")

        val participants =
            OdinSystemSerializer.deserialize<ConversationAppDataJson>(
                appData.content ?: error("Missing content")
            ).recipients

        val uniqueId = appData.uniqueId
            ?: error("Missing uniqueId")

        // 1️⃣ Conversation custom image
        val imagePayload = metadata.payloads
            ?.firstOrNull { it.key == ChatProtocol.ConversationImageKey }


        if (imagePayload != null) {
            val imageSize: ImageSize = ImageSize.THUMB_MEDIUM

            val imageData = HomebaseImageData(
                driveId = chatDrive,
                fileId = conversation.fileId,
                payloadKey = imagePayload.key,
                isEncrypted = metadata.isEncrypted,
                previewThumbnail = imagePayload.previewThumbnail?.toEmbeddedThumb()
                    ?: appData.previewThumbnail,
                keyHeader = KeyHeader(
                    iv = Base64.decode(
                        imagePayload.iv
                            ?: throw IllegalStateException("encrypted payload requires key header")
                    ),
                    aesKey = conversation.keyHeader.aesKey
                ),
                requestedSize = imageSize,
                lastModified = imagePayload.lastModified,
            )

            return ConversationAvatarModel(
                type = ConversationAvatarModel.Type.ConversationImage,
                imageData = imageData
            )
        }

        // 2️⃣ Self conversation (fixed ID)
        if (uniqueId == ChatProtocol.ConversationWithYourselfId) {
            return ConversationAvatarModel(
                odinId = domain,
                type = ConversationAvatarModel.Type.Owner
            )
        }

        val others = participants.filter { it != domain }

        // 3️⃣ 1:1
        if (others.size == 1) {
            return ConversationAvatarModel(
                type = ConversationAvatarModel.Type.Connection,
                odinId = others.first()
            )
        }

        // 4️⃣ Group fallback
        return ConversationAvatarModel(
            type = ConversationAvatarModel.Type.GroupFallback
        )
    }
}


