package id.homebase.chat.services.convo

import co.touchlab.kermit.Logger
import id.homebase.api.client.KeyHeader
import id.homebase.api.client.auth.CredentialsManager
import id.homebase.api.client.connections.ConnectionIntroductionProvider
import id.homebase.api.client.connections.IntroductionGroup
import id.homebase.api.client.drives.HomebaseFile
import id.homebase.api.client.drives.QueryBatchSortField
import id.homebase.api.client.drives.QueryBatchSortOrder
import id.homebase.api.client.drives.files.PayloadFile
import id.homebase.api.client.drives.files.ThumbnailFile
import id.homebase.api.client.drives.upload.DriveUploadProvider
import id.homebase.api.client.drives.upload.EmbeddedThumb
import id.homebase.api.client.drives.upload.FileUpdateInstructionSet
import id.homebase.api.client.drives.upload.TransitOptions
import id.homebase.api.client.drives.upload.UpdateFileByUniqueIdRequest
import id.homebase.api.client.drives.upload.UpdateLocale
import id.homebase.api.client.drives.upload.UpdateManifest
import id.homebase.api.client.drives.upload.UploadAppFileMetaData
import id.homebase.api.client.drives.upload.UploadFileMetadata
import id.homebase.api.client.drives.upload.UploadFileRequest
import id.homebase.api.common.OdinId
import id.homebase.api.common.time.UnixTimeUtc
import id.homebase.api.crypto.ByteArrayUtil
import id.homebase.api.serialization.OdinSystemSerializer
import id.homebase.api.sync.database.DatabaseManager
import id.homebase.api.sync.database.QueryBatch
import id.homebase.chat.data.ConversationUiModel
import id.homebase.chat.services.ChatMessageStream
import id.homebase.chat.services.ChatProtocol
import id.homebase.chat.services.PayloadBundle
import id.homebase.chat.services.PayloadBundleEncryptionService
import id.homebase.chat.services.XorIdUtil
import id.homebase.core.avatars.ConversationAvatarModel
import id.homebase.core.config.chatTargetDrive
import id.homebase.core.image.HomebaseImageData
import id.homebase.core.image.ImageSize
import kotlin.io.encoding.Base64
import kotlin.uuid.Uuid
import kotlinx.coroutines.CoroutineScope

class ConversationService(
    private val credentialsManager: CredentialsManager,
    private val driveUploadProvider: DriveUploadProvider,
    private val payloadBundleEncryptionService: PayloadBundleEncryptionService,
    private val dbm: DatabaseManager,
    private val contactService: ContactService,
    private val introductionProvider: ConnectionIntroductionProvider,
    private val scope: CoroutineScope
) {
    private val chatDrive = chatTargetDrive.alias

    suspend fun createConversation(
        recipients: List<OdinId>,
        title: String?,
        payloadBundle: PayloadBundle?
    ): Uuid {

        val domain = credentialsManager.requireActiveDomain()
        val isGroup = recipients.size > 1
        val keyHeader = KeyHeader.newRandom16()

        val newConversationId: Uuid =
            if (isGroup) {
                Uuid.random()
            } else {
                XorIdUtil.getNewXorId(domain.domainName, recipients.first().domainName)
            }

        val existingConversation = getConversation(newConversationId)
        if (existingConversation != null) {
            return newConversationId
        }

        val content =
            ConversationAppDataJson(
                title = title ?: "",
                recipients = (recipients + domain).distinct(),
                version = 1,
                admins = listOf(domain)
            )

        val encryptedBundle =
            payloadBundleEncryptionService.encryptBundle(
                newConversationId,
                payloadBundle,
                keyHeader.aesKey,
                scope
            )

        val metadata =
            UploadFileMetadata(
                allowDistribution = true,
                isEncrypted = true,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = newConversationId,
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail =
                            encryptedBundle.previewThumbs.minByOrNull {
                                it.pixelWidth
                            } // TODO:need to get the embeded thum generated by
                        // the thumbnail creator
                    ),
            )

        val request =
            UploadFileRequest(
                driveId = chatDrive,
                keyHeader = keyHeader,
                metadata = metadata.encryptContent(keyHeader),
                transitOptions =
                    TransitOptions(recipients = recipients, useAppNotification = false),
                payloads = encryptedBundle.payloads,
                thumbnails = encryptedBundle.thumbnails
            )

        driveUploadProvider.uploadFile(request)

        if (isGroup) {
            trySendIntroductions(recipients, "$domain has added you to a group chat")
        }

        return newConversationId
    }

    suspend fun requireConversation(conversationId: Uuid): ConversationUiModel {
        return getConversation(conversationId)
            ?: throw IllegalStateException("No conversation found")
    }

    suspend fun getConversation(conversationId: Uuid): ConversationUiModel? {
        val file = getConversationHomebaseFile(conversationId) ?: return null
        return mapToConversationUi(file, null)
    }

    suspend fun updateAdmins(
        conversationId: Uuid,
        add: List<OdinId> = emptyList(),
        remove: List<OdinId> = emptyList()
    ) {
        val conversation = requireConversation(conversationId)
        val domain = credentialsManager.requireActiveDomain()

        requireCallerIsGroupAdmin(conversation)

        val recipients = conversation.participants
        val admins = conversation.admins.toMutableSet()

        // additions must already be participants
        require(add.all { recipients.contains(it) }) {
            "Admins must be recipients"
        }

        admins.addAll(add)
        admins.removeAll(remove)

        if (admins.isEmpty()) {
            throw IllegalStateException("Conversation must have at least one admin")
        }

        // forbid removing yourself if you would leave zero admins
        if (remove.contains(domain) && !admins.contains(domain)) {
            if (admins.size == 0) {
                throw IllegalStateException("Cannot remove the last admin.  You must first add another to replace you")
            }
        }

        updateConversationInternal(
            conversationId = conversationId,
            title = conversation.name,
            recipients = recipients,
            admins = admins
        )
    }

    suspend fun updateGroupMembers(
        conversationId: Uuid,
        add: List<OdinId> = emptyList(),
        remove: List<OdinId> = emptyList()
    ) {
        val conversation = requireConversation(conversationId)
        requireCallerIsGroupAdmin(conversation)

        val domain = credentialsManager.requireActiveDomain()
        val current = conversation.participants.toMutableSet()

        val removed = current.intersect(remove.toSet())
        current.removeAll(remove)

        val added = add.filterNot { current.contains(it) }
        current.addAll(added)

        val normalized = (current + domain).distinct()

        updateConversationInternal(
            conversationId = conversationId,
            title = conversation.name,
            recipients = normalized
        )

        trySendIntroductions(added, "$domain has added you to a group chat")

        //TODO: send a chat message for each member added or removed
    }

    suspend fun updateConversation(
        conversationId: Uuid,
        title: String?,
        payloadBundle: PayloadBundle? = null
    ) {
        val conversation = requireConversation(conversationId)

        if(conversation.isGroupConversation)
        {
            requireCallerIsGroupAdmin(conversation)
        }

        updateConversationInternal(
            conversationId = conversationId,
            title = title,
            recipients = conversation.participants,
            payloadBundle = payloadBundle
        )

        //TODO: notify via chat messages the conversation changed
//        val domain = credentialsManager.requireActiveDomain()
    }

    suspend fun updateConversationInternal(
        conversationId: Uuid,
        title: String?,
        recipients: List<OdinId>,
        admins: Set<OdinId>? = null,
        payloadBundle: PayloadBundle? = null
    ) {
        val credentials = credentialsManager.requireActiveCredentials()
        val domain = credentials.domain

        val conversationFile = getConversationHomebaseFile(conversationId)
            ?: error("No conversation found")

        val conversation = requireConversation(conversationId)

        // Always include self but remember to never distribute to self
        val normalizedRecipients = (recipients + domain).distinct()
        val keyHeader = KeyHeader(
            iv = ByteArrayUtil.getRndByteArray(16),
            aesKey = conversationFile.keyHeader.aesKey
        )

        val content =
            ConversationAppDataJson(
                title = title ?: "",
                recipients = normalizedRecipients,
                admins = admins?.toList() ?: conversation.admins.toList(),
                version = 1 // logical version; server enforces via versionTag
            )

        var manifest: UpdateManifest
        var previewThumb: EmbeddedThumb?
        var payloads: List<PayloadFile>?
        var thumbs: List<ThumbnailFile>?

        if (payloadBundle == null) {
            manifest = UpdateManifest.build(
                payloads = null,
                toDeletePayloads = null,
                thumbnails = null,
                generatePayloadIv = false
            )

            payloads = emptyList()
            thumbs = emptyList()
            previewThumb = conversationFile.fileMetadata.appData.previewThumbnail

        } else {

            val encryptedBundle =
                payloadBundleEncryptionService.encryptBundle(
                    conversationId,
                    payloadBundle,
                    keyHeader.aesKey,
                    scope
                )

            payloads = encryptedBundle.payloads
            thumbs = encryptedBundle.thumbnails

            manifest =
                UpdateManifest.build(
                    payloads = payloads,
                    toDeletePayloads = null,
                    thumbnails = encryptedBundle.thumbnails,
                    generatePayloadIv = false
                )

            previewThumb = encryptedBundle.previewThumbs.minByOrNull {
                it.pixelWidth
            }
        }

        val metadata =
            UploadFileMetadata(
                allowDistribution = true, // todo: base on transfer history as optimization
                isEncrypted = true,
                versionTag = conversationFile.fileMetadata.versionTag,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = conversationId,
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail = previewThumb
                    )
            )

        val instructions =
            FileUpdateInstructionSet(
                transferIv = ByteArrayUtil.getRndByteArray(16),
                locale = UpdateLocale.Local,
                recipients = recipients.filterNot { it == domain },
                manifest = manifest
            )

        val request =
            UpdateFileByUniqueIdRequest(
                driveId = chatDrive,
                uniqueId = conversationId,
                keyHeader = keyHeader,
                instructions = instructions,
                metadata = metadata.encryptContent(keyHeader),
                payloads = payloads,
                thumbnails = thumbs
            )

        driveUploadProvider.updateFileByUniqueId(
            request = request,
            onVersionConflict = {
                // caller decides retry strategy; surface conflict cleanly
                null
            }
        )
    }

    suspend fun introduceEveryone(conversationId: Uuid, message: String?) {
        val conversation = requireConversation(conversationId)
        trySendIntroductions(conversation.participants, message ?: "")
    }

    private suspend fun trySendIntroductions(
        recipients: List<OdinId>,
        message: String
    ) {
        try {
            // send introductions
            introductionProvider.sendIntroductions(
                group = IntroductionGroup(
                    recipients = recipients,
                    message = message
                )
            )
        } catch (t: Throwable) {
            Logger.e("Failed sending introductions", t)
        }
    }

    private suspend fun requireCallerIsGroupAdmin(conversation: ConversationUiModel) {
        val domain = credentialsManager.requireActiveDomain()

        if (!conversation.isGroupConversation) {
            throw IllegalStateException("Must be a group conversations")
        }

        if (!conversation.admins.contains(domain)) {
            throw IllegalStateException("Only group admins can perform this action")
        }
    }

    private suspend fun getConversationHomebaseFile(conversationId: Uuid): HomebaseFile? {

        val c = credentialsManager.requireActiveCredentials()
        val queryBatch = QueryBatch(c.getIdentityId())

        val result =
            queryBatch.queryBatchAsync(
                dbm = dbm,
                driveId = chatDrive,
                noOfItems = 1,
                cursor = null,
                sortOrder = QueryBatchSortOrder.NewestFirst,
                sortField = QueryBatchSortField.CreatedDate,
                fileSystemType = 0,
                uniqueIdAnyOf = listOf(conversationId),
                filetypesAnyOf = listOf(ChatProtocol.ConversationFileType),
            )

        val file = result.records.firstOrNull()
        return file
    }

    suspend fun mapToConversationUi(
        conversationFile: HomebaseFile,
        lastMsg: HomebaseFile?
    ): ConversationUiModel {

        return try {

            val metadata = conversationFile.fileMetadata
            val appData = metadata.appData

            if (appData.fileType != ChatProtocol.ConversationFileType) {
                throw IllegalArgumentException("Not a conversation file")
            }

            val conversationData =
                OdinSystemSerializer.deserialize<ConversationAppDataJson>(
                    appData.content ?: error("Conversation appData missing")
                )

            val domain = credentialsManager.getActiveDomain() ?: error("No active domain")

            val localAppData =
                metadata.localAppData?.content?.let {
                    OdinSystemSerializer.deserialize<ConversationLocalAppDataJson>(it)
                }

            val participants = conversationData.recipients

            val displayNames =
                participants.map { odinId ->
                    contactService.resolveByOdinId(odinId)?.name ?: odinId.domainName
                }

            val title =
                if (participants.size == 2) {
                    val other = participants.first { it != domain }
                    contactService.resolveByOdinId(other)?.name ?: "fracko"
                } else {
                    conversationData.title ?: displayNames.joinToString(", ")
                }

            val admins = (conversationData.admins ?: listOf(
                conversationFile.fileMetadata.originalAuthor
                    ?: error("Conversation missing original author")
            )).toSet()

            val avatarModel = buildConversationAvatarModel(conversationFile)

            val ui =
                ConversationUiModel(
                    id = appData.uniqueId ?: error("Missing uniqueId"),
                    name = title,
                    lastMessage = " ",
                    timestamp = UnixTimeUtc(0).toInstant(),
                    unreadCount = 0,
                    avatarTiny = appData.previewThumbnail,
                    avatarInitials = "",
                    avatarUrl = "",
                    participants = participants,
                    lastRead = localAppData?.lastReadTime?.toInstant()
                        ?: UnixTimeUtc(0).toInstant(),
                    avatarModel = avatarModel,
                    admins = admins
                )

            if (lastMsg != null) {
                ChatMessageStream.mapToMessageData(lastMsg, ::resolveDisplayName)?.let {
                    ui.updateWithLatestMessage(it, domain)
                }
            }

            ui

        } catch (t: Throwable) {

            Logger.e("Failed mapping conversation UI", t)

            ConversationUiModel(
                id = conversationFile.fileMetadata.appData.uniqueId ?: Uuid.random(),
                name = "",
                lastMessage = "Failure loading conversation",
                timestamp = UnixTimeUtc(0).toInstant(),
                unreadCount = 0,
                avatarInitials = "",
                avatarUrl = "",
                avatarTiny = null,
                participants = emptyList(),
                lastRead = UnixTimeUtc(0).toInstant(),
                avatarModel = ConversationAvatarModel(type = ConversationAvatarModel.Type.GroupFallback),
                admins = emptySet()
            )
        }
    }

    private suspend fun resolveDisplayName(file: HomebaseFile): String {
        val author = file.fileMetadata.originalAuthor ?: return ""

        return contactService.resolveByOdinId(author)?.name ?: author.domainName
    }


    private suspend fun buildConversationAvatarModel(
        conversation: HomebaseFile
    ): ConversationAvatarModel {

        val metadata = conversation.fileMetadata
        val appData = metadata.appData

        val domain = credentialsManager.getActiveDomain() ?: error("No active domain")

        val participants =
            OdinSystemSerializer.deserialize<ConversationAppDataJson>(
                appData.content ?: error("Missing content")
            )
                .recipients

        val uniqueId = appData.uniqueId ?: error("Missing uniqueId")

        // 1️⃣ Conversation custom image
        val imagePayload =
            metadata.payloads?.firstOrNull { it.key == ChatProtocol.ConversationImageKey }

        if (imagePayload != null) {
            val imageSize: ImageSize = ImageSize.THUMB_MEDIUM

            val imageData =
                HomebaseImageData(
                    driveId = chatDrive,
                    fileId = conversation.fileId,
                    payloadKey = imagePayload.key,
                    isEncrypted = metadata.isEncrypted,
                    previewThumbnail = imagePayload.previewThumbnail?.toEmbeddedThumb()
                        ?: appData.previewThumbnail,
                    keyHeader =
                        KeyHeader(
                            iv =
                                Base64.decode(
                                    imagePayload.iv
                                        ?: throw IllegalStateException(
                                            "encrypted payload requires key header"
                                        )
                                ),
                            aesKey = conversation.keyHeader.aesKey
                        ),
                    requestedSize = imageSize,
                    lastModified = imagePayload.lastModified,
                )

            return ConversationAvatarModel(
                type = ConversationAvatarModel.Type.ConversationImage,
                imageData = imageData
            )
        }

        // 2️⃣ Self conversation (fixed ID)
        if (uniqueId == ChatProtocol.ConversationWithYourselfId) {
            return ConversationAvatarModel(
                odinId = domain,
                type = ConversationAvatarModel.Type.Owner
            )
        }

        val others = participants.filter { it != domain }

        // 3️⃣ 1:1
        if (others.size == 1) {
            return ConversationAvatarModel(
                type = ConversationAvatarModel.Type.Connection,
                odinId = others.first()
            )
        }

        // 4️⃣ Group fallback
        return ConversationAvatarModel(type = ConversationAvatarModel.Type.GroupFallback)
    }
}
