package id.homebase.chat.services.convo

import co.touchlab.kermit.Logger
import id.homebase.api.client.KeyHeader
import id.homebase.api.client.auth.CredentialsManager
import id.homebase.api.client.connections.ConnectionIntroductionProvider
import id.homebase.api.client.connections.IntroductionGroup
import id.homebase.api.client.drives.HomebaseFile
import id.homebase.api.client.drives.QueryBatchSortField
import id.homebase.api.client.drives.QueryBatchSortOrder
import id.homebase.api.client.drives.files.PayloadFile
import id.homebase.api.client.drives.files.ThumbnailFile
import id.homebase.api.client.drives.upload.EmbeddedThumb
import id.homebase.api.client.drives.upload.FileUpdateInstructionSet
import id.homebase.api.client.drives.upload.TransitOptions
import id.homebase.api.client.drives.upload.UpdateFileByUniqueIdRequest
import id.homebase.api.client.drives.upload.UpdateLocale
import id.homebase.api.client.drives.upload.UpdateManifest
import id.homebase.api.client.drives.upload.UploadAppFileMetaData
import id.homebase.api.client.drives.upload.UploadFileMetadata
import id.homebase.api.client.drives.upload.UploadFileRequest
import id.homebase.api.common.OdinId
import id.homebase.api.crypto.ByteArrayUtil
import id.homebase.api.serialization.OdinSystemSerializer
import id.homebase.api.sync.database.DatabaseManager
import id.homebase.api.sync.database.OutboxSync
import id.homebase.api.sync.database.QueryBatch
import id.homebase.chat.data.ConversationUiModel
import id.homebase.chat.services.ChatMessageSenderService
import id.homebase.chat.services.ChatProtocol
import id.homebase.chat.services.PayloadBundle
import id.homebase.chat.services.PayloadBundleEncryptionService
import id.homebase.chat.services.XorIdUtil
import id.homebase.core.config.chatTargetDrive
import kotlin.uuid.Uuid
import kotlinx.coroutines.CoroutineScope
import kotlin.collections.plus

class ConversationService(
    private val credentialsManager: CredentialsManager,
    private val payloadBundleEncryptionService: PayloadBundleEncryptionService,
    private val dbm: DatabaseManager,
    private val contactService: ContactService,
    private val introductionProvider: ConnectionIntroductionProvider,
    private val scope: CoroutineScope,
    private val outboxSync: OutboxSync,
    private val chatMessageSenderService: ChatMessageSenderService
) {
    private val chatDrive = chatTargetDrive.alias

    private val mapper: ConversationMapper = ConversationMapper(
        credentialsManager = credentialsManager,
        contactService = contactService
    )

    suspend fun createConversation(
        recipients: List<OdinId>,
        title: String?,
        payloadBundle: PayloadBundle?
    ): Uuid {

        val domain = credentialsManager.requireActiveDomain()
        val isGroup = recipients.size > 1
        val keyHeader = KeyHeader.newRandom16()

        val newConversationId: Uuid =
            if (isGroup) {
                Uuid.random()
            } else {
                XorIdUtil.getNewXorId(domain.domainName, recipients.first().domainName)
            }

        val existingConversation = getConversation(newConversationId)
        if (existingConversation != null) {
            return newConversationId
        }

        val content =
            ConversationAppDataJson(
                title = title ?: "",
                recipients = (recipients + domain).distinct(),
                version = 1,
                admins = listOf(domain)
            )

        val encryptedBundle =
            payloadBundleEncryptionService.encryptBundle(
                newConversationId,
                payloadBundle,
                keyHeader.aesKey,
                scope
            )

        val metadata =
            UploadFileMetadata(
                allowDistribution = true,
                isEncrypted = true,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = newConversationId,
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail =
                            encryptedBundle.previewThumbs.minByOrNull {
                                it.pixelWidth
                            } // TODO:need to get the embedded thum generated by
                        // the thumbnail creator
                    ),
            )

        val request =
            UploadFileRequest(
                driveId = chatDrive,
                keyHeader = keyHeader,
                metadata = metadata.encryptContent(keyHeader),
                transitOptions =
                    TransitOptions(recipients = recipients, useAppNotification = false),
                payloads = encryptedBundle.payloads,
                thumbnails = encryptedBundle.thumbnails
            )

        val enqueued = outboxSync.tryEnqueue(request)

        if (!enqueued) {
            error("failed to create conversation")
        }

        if (isGroup) {
            trySendIntroductions(recipients, "$domain has added you to a group chat")

            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = Uuid.random(),
                conversationId = newConversationId,
                messageText = "$domain started this group titled $title"
            )
        }

        return newConversationId
    }

    suspend fun requireConversation(conversationId: Uuid): ConversationUiModel {
        return getConversation(conversationId)
            ?: throw IllegalStateException("No conversation found")
    }

    suspend fun getConversation(conversationId: Uuid): ConversationUiModel? {
        val file = getConversationHomebaseFile(conversationId) ?: return null
        return mapper.mapToConversationUi(file, null)
    }

    suspend fun updateAdmins(
        conversationId: Uuid,
        add: List<OdinId> = emptyList(),
        remove: List<OdinId> = emptyList()
    ) {
        val conversation = requireConversation(conversationId)
        val domain = credentialsManager.requireActiveDomain()

        requireCallerIsGroupAdmin(conversation)

        val recipients = conversation.participants
        val admins = conversation.admins.toMutableSet()

        // additions must already be participants
        require(add.all { recipients.contains(it) }) {
            "Admins must be recipients"
        }

        admins.addAll(add)
        admins.removeAll(remove)

        if (admins.isEmpty()) {
            throw IllegalStateException("Conversation must have at least one admin")
        }

        // forbid removing yourself if you would leave zero admins
        if (remove.contains(domain) && !admins.contains(domain)) {
            if (admins.size == 0) {
                throw IllegalStateException("Cannot remove the last admin.  You must first add another to replace you")
            }
        }

        updateConversationInternal(
            conversationId = conversationId,
            title = conversation.name,
            recipients = recipients,
            admins = admins
        )

        var previousMessageId: Uuid? = null
        add.forEach { user ->
            val messageId = Uuid.random()
            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain added ${user.domainName}",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }

        remove.forEach { user ->
            val messageId = Uuid.random()
            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain removed ${user.domainName}",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }

    }

    suspend fun updateGroupMembers(
        conversationId: Uuid,
        add: List<OdinId> = emptyList(),
        remove: List<OdinId> = emptyList()
    ) {
        val conversation = requireConversation(conversationId)
        requireCallerIsGroupAdmin(conversation)

        val domain = credentialsManager.requireActiveDomain()
        val current = conversation.participants.toMutableSet()

        val removed = current.intersect(remove.toSet())
        current.removeAll(remove)

        val added = add.filterNot { current.contains(it) }
        current.addAll(added)

        val normalized = (current + domain).distinct()

        updateConversationInternal(
            conversationId = conversationId,
            title = conversation.name,
            recipients = normalized
        )

        trySendIntroductions(added, "$domain has added you to a group chat")

        var previousMessageId: Uuid? = null
        added.forEach { user ->
            val messageId = Uuid.random()
            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain added ${user.domainName}",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }

        removed.forEach { user ->
            val messageId = Uuid.random()
            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain removed ${user.domainName}",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }
    }

    suspend fun updateConversation(
        conversationId: Uuid,
        title: String?,
        payloadBundle: PayloadBundle? = null
    ) {
        val conversation = requireConversation(conversationId)

        if (conversation.isGroupConversation) {
            requireCallerIsGroupAdmin(conversation)
        }

        updateConversationInternal(
            conversationId = conversationId,
            title = title,
            recipients = conversation.participants,
            payloadBundle = payloadBundle
        )

        var previousMessageId: Uuid? = null
        val domain = credentialsManager.requireActiveDomain()

        if (title != null && title != conversation.name) {

            val messageId = Uuid.random()

            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain changed the conversation title to \"$title\"",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }

        if (payloadBundle != null) {

            val messageId = Uuid.random()

            chatMessageSenderService.sendStatusMessage(
                messageUniqueId = messageId,
                conversationId = conversationId,
                messageText = "$domain updated the conversation photo",
                previousMessageUniqueId = previousMessageId
            )

            previousMessageId = messageId
        }

    }

    suspend fun updateConversationInternal(
        conversationId: Uuid,
        title: String?,
        recipients: List<OdinId>,
        admins: Set<OdinId>? = null,
        payloadBundle: PayloadBundle? = null
    ) {
        val credentials = credentialsManager.requireActiveCredentials()
        val domain = credentials.domain

        val conversationFile = getConversationHomebaseFile(conversationId)
            ?: error("No conversation found")

        val conversation = requireConversation(conversationId)

        // Always include self but remember to never distribute to self
        val normalizedRecipients = (recipients + domain).distinct()
        val keyHeader = KeyHeader(
            iv = ByteArrayUtil.getRndByteArray(16),
            aesKey = conversationFile.keyHeader.aesKey
        )

        val content =
            ConversationAppDataJson(
                title = title ?: "",
                recipients = normalizedRecipients,
                admins = admins?.toList() ?: conversation.admins.toList(),
                version = 1 // logical version; server enforces via versionTag
            )

        var manifest: UpdateManifest
        var previewThumb: EmbeddedThumb?
        var payloads: List<PayloadFile>?
        var thumbs: List<ThumbnailFile>?

        if (payloadBundle == null) {
            manifest = UpdateManifest.build(
                payloads = null,
                toDeletePayloads = null,
                thumbnails = null,
                generatePayloadIv = false
            )

            payloads = emptyList()
            thumbs = emptyList()
            previewThumb = conversationFile.fileMetadata.appData.previewThumbnail

        } else {

            val encryptedBundle =
                payloadBundleEncryptionService.encryptBundle(
                    conversationId,
                    payloadBundle,
                    keyHeader.aesKey,
                    scope
                )

            payloads = encryptedBundle.payloads
            thumbs = encryptedBundle.thumbnails

            manifest =
                UpdateManifest.build(
                    payloads = payloads,
                    toDeletePayloads = null,
                    thumbnails = encryptedBundle.thumbnails,
                    generatePayloadIv = false
                )

            previewThumb = encryptedBundle.previewThumbs.minByOrNull {
                it.pixelWidth
            }
        }

        val metadata =
            UploadFileMetadata(
                allowDistribution = true, // todo: base on transfer history as optimization
                isEncrypted = true,
                versionTag = conversationFile.fileMetadata.versionTag,
                appData =
                    UploadAppFileMetaData(
                        uniqueId = conversationId,
                        fileType = ChatProtocol.ConversationFileType,
                        content = OdinSystemSerializer.serialize(content),
                        previewThumbnail = previewThumb
                    )
            )

        val instructions =
            FileUpdateInstructionSet(
                transferIv = ByteArrayUtil.getRndByteArray(16),
                locale = UpdateLocale.Local,
                recipients = recipients.filterNot { it == domain },
                manifest = manifest
            )

        val request =
            UpdateFileByUniqueIdRequest(
                driveId = chatDrive,
                uniqueId = conversationId,
                keyHeader = keyHeader,
                instructions = instructions,
                metadata = metadata.encryptContent(keyHeader),
                payloads = payloads,
                thumbnails = thumbs
            )

        val enqueued = outboxSync.tryEnqueue(request)
        if (!enqueued) {
            error("Failed to update conversation")
        }
    }

    suspend fun introduceEveryone(conversationId: Uuid, message: String?) {
        val conversation = requireConversation(conversationId)
        trySendIntroductions(conversation.participants, message ?: "")
    }

    private suspend fun trySendIntroductions(
        recipients: List<OdinId>,
        message: String
    ) {
        try {
            // send introductions
            introductionProvider.sendIntroductions(
                group = IntroductionGroup(
                    recipients = recipients,
                    message = message
                )
            )
        } catch (t: Throwable) {
            Logger.e("Failed sending introductions", t)
        }
    }

    private suspend fun requireCallerIsGroupAdmin(conversation: ConversationUiModel) {
        val domain = credentialsManager.requireActiveDomain()

        if (!conversation.isGroupConversation) {
            throw IllegalStateException("Must be a group conversations")
        }

        if (!conversation.admins.contains(domain)) {
            throw IllegalStateException("Only group admins can perform this action")
        }
    }

    private suspend fun getConversationHomebaseFile(conversationId: Uuid): HomebaseFile? {

        val c = credentialsManager.requireActiveCredentials()
        val queryBatch = QueryBatch(c.getIdentityId())

        val result =
            queryBatch.queryBatchAsync(
                dbm = dbm,
                driveId = chatDrive,
                noOfItems = 1,
                cursor = null,
                sortOrder = QueryBatchSortOrder.NewestFirst,
                sortField = QueryBatchSortField.CreatedDate,
                fileSystemType = 0,
                uniqueIdAnyOf = listOf(conversationId),
                filetypesAnyOf = listOf(ChatProtocol.ConversationFileType),
            )

        val file = result.records.firstOrNull()
        return file
    }
}
