include required("conveyor_common.conf")

app {
  // The base URL is where the download site will be placed. Packages will check here for updates.
  site {
    base-url = "https://github.com/homebase-id/chat-desktop-release-bleeding/releases/latest/download"
    github.oauth-token = ${env.CONVEYOR_GITHUB_TOKEN}
  }

  // This is optional. If not specified the last component of the rdns name will be turned into a display name.
  display-name = "Homebase Chat Dev"
  vendor = "Homebase"
  contact-email = "apps@vidence.co"

  // A global identifier for the app.
  rdns-name = "id.homebase.feed.dev"

  // For iteration speed. Remove for release.
  compression-level = low

  jvm {
    system-properties {
      "app.rdns.name" = "id.homebase.feed.dev"
    }
  }
}
