// This is a hashbang include. You can run the command after the #! to see what
// configuration is being extracted from the Gradle build using the Conveyor plugin.
include "#!./gradlew -q printConveyorConfig"

// This enables native library extraction, which improves app startup time and robustness.
// It is optional but a good idea to have it. You can remove this if you get tired of specifying
// system properties for Java libraries with native components.
//
// See https://hydraulic.dev/blog/11-in-jar-signing.html for more.
include required("https://raw.githubusercontent.com/hydraulic-software/conveyor/master/configs/jvm/extract-native-libraries.conf")

// Config file documentation: https://conveyor.hydraulic.dev/latest/configs

gradle-cache = ${env.HOME}/.gradle

app {
   // Add Linux Arm support
   machines = [ windows.amd64, mac.amd64, mac.aarch64, linux.amd64.glibc, linux.aarch64.glibc ]

  // Project repo url (open-source if free to use with Conveyor)
  vcs-url = "https://github.com/homebase-id/chat-kmp"

  // The base URL is where the download site will be placed. Packages will check here for updates.
  site {
    base-url = "https://github.com/homebase-id/chat-desktop-release-bleeding/releases/latest/download"
    github.oauth-token = ${env.CONVEYOR_GITHUB_TOKEN}
  }

  // This is optional. If not specified the last component of the rdns name will be turned into a display name.
  display-name = "Homebase Chat Dev"
  vendor = "Homebase"
  contact-email = "apps@vidence.co"

  // A global identifier for the app.
  rdns-name = "id.homebase.feed.dev"

  // Use the Compose logo as an icon and include it so we can pass it to the Window constructor.
  icons = icons/homebase.svg
  #windows.inputs += TASK/rendered-icons/windows
  #linux.inputs += TASK/rendered-icons/linux

  // For iteration speed. Remove for release.
  compression-level = low

  // https://conveyor.hydraulic.dev/20.0/configs/update-modes/
  updates = aggressive

  // Will register the URL scheme.
  #url-schemes = [ "homebase" ]

  jvm {
    extract-native-libraries = true
    jna.library.path = <libpath>

    system-properties {
      // Force PicoCLI to always use ANSI mode even on
      // Windows, where our launcher enables them.
      picocli.ansi = tty

      // Read HTTP proxy settings from the OS.
      java.net.useSystemProxies = true
    }

    #options += -Xmx1024m

    // Needed for Ed25519 provider and modern SSL.
    modules += jdk.crypto.ec
  }

  mac {
    info-plist {
      LSMinimumSystemVersion = 15.0
    }
  }

  windows {
    start-on-login = true
  }
}

conveyor {
  compatibility-level = 21
}
