version.name=1.3.1280
version.code.base=1280

# In Github actions we will generate version.name like MAJOR.MINOR.[version.code.base + BUILD_NUMBER]
#
# So for example if these are the values in version.properties:
# version.name=1.3.1200
# version.code.base=1200
#
# And the Github action build number = 7
#
# This will result in version.name = 1.3.1207
