import org.apache.tools.ant.filters.ReplaceTokens
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpack
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// Sub-path mount support. Pass -PpublicPath=/apps/chat-wasm/ to host the bundle under a sub-path
// (odin-core's CI does this); defaults to "/" for standalone runs. The normalized value flows to:
//   - webpack `output.publicPath` (via the generated webpack.config.d/00-publicPath.js)
//   - the <base href> injected into index.html (via processResources token substitution)
//   - the dev-server historyApiFallback rewrite (devserver.js reads globalThis.WEBAPP_PUBLIC_PATH)
//   - the YouAuth redirect URI at runtime (RedirectConfig.web.kt reads document.baseURI)
val publicPath: String = (providers.gradleProperty("publicPath").orNull ?: "/").let { raw ->
    val withLeading = if (raw.startsWith("/")) raw else "/$raw"
    if (withLeading.endsWith("/")) withLeading else "$withLeading/"
}

val generateWebpackPublicPathConfig by tasks.registering {
    val outFile = layout.projectDirectory.file("webpack.config.d/00-publicPath.js").asFile
    inputs.property("publicPath", publicPath)
    outputs.file(outFile)
    doLast {
        outFile.parentFile.mkdirs()
        outFile.writeText(
            """
            // AUTO-GENERATED by webApp/build.gradle.kts from -PpublicPath. Do not edit.
            // The alphabetic 00- prefix ensures this file is loaded before sibling config.d files.
            globalThis.WEBAPP_PUBLIC_PATH = '$publicPath';
            config.output = Object.assign({}, config.output, { publicPath: '$publicPath' });
            """.trimIndent() + "\n"
        )
    }
}

// HtmlWebpackPlugin owns index.html so it can substitute the content-hashed bundle filename into
// the bootstrap script. We pull index.html OUT of the resource pipeline (so it's not also copied
// into processedResources -> dist) and instead pre-substitute @PUBLIC_PATH@ into a template under
// build/generated, which HtmlWebpackPlugin reads as its template input.
val htmlTemplateDir = layout.buildDirectory.dir("generated/html-template")
val generateHtmlTemplate by tasks.registering(Copy::class) {
    from(layout.projectDirectory.file("src/wasmJsMain/resources/index.html"))
    into(htmlTemplateDir)
    inputs.property("publicPath", publicPath)
    filter<ReplaceTokens>("tokens" to mapOf("PUBLIC_PATH" to publicPath))
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        binaries.executable()
        browser {
            commonWebpackConfig {
                outputFileName = "homebase-app.js"
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    static(project.projectDir.path)
                }
            }
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain.dependencies {
            implementation(project(":homebase-common"))
            implementation(project(":homebase-chat"))
            implementation(project(":homebase-core"))

            implementation(libs.jetbrains.compose.runtime)
            implementation(libs.jetbrains.compose.foundation)
            implementation(libs.jetbrains.compose.resources)
            implementation(libs.jetbrains.compose.material3)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.navigation.compose)
            implementation(libs.koin.core)

        }
        wasmJsMain.dependencies {
            // Used by webpack.config.d/html-plugin.js to inject the (content-hashed) bundle
            // filename into index.html. Webpack-only — never reaches the wasm output.
            implementation(devNpm("html-webpack-plugin", "5.6.0"))
        }
    }
}

tasks.named<Copy>("wasmJsProcessResources") {
    // index.html is owned by HtmlWebpackPlugin (see generateHtmlTemplate). Excluding it here
    // prevents a second copy from landing in dist/ alongside the HtmlWebpackPlugin output.
    exclude("index.html")
}

tasks.withType<KotlinWebpack>().configureEach {
    dependsOn(generateWebpackPublicPathConfig, generateHtmlTemplate)
}

