name: Build iOS Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"

      - name: Build iOS
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: iosApp/iosApp.xcodeproj
          workspace-path: iosApp/iosApp.xcodeproj/project.xcworkspace
          scheme: iosApp
          export-options: iosApp/options.plist
          p12-base64: ${{ secrets.IOS_FEED_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.FEED_IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_FEED_CERTIFICATE_PASSWORD }}

      - name: Rename IPA
        run: mv output.ipa iosApp.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: iosApp.ipa