name: Build iOS Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"

      - name: Extract package version
        id: version
        uses: Saionaro/extract-package-version@v1.2.1
        with:
          path: packages/mobile

      - name: Auth GitHub Packages
        run: |
          echo "@homebase-id:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install npm deps
        run: npm ci

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: packages/mobile
          ruby-version: "3.1"
          bundler-cache: true

      - name: Bump iOS version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.version.outputs.version }}
          build-number: ${{ github.run_number }}
          project-path: packages/mobile/ios

      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: packages/mobile/ios/Podfile.lock

      - name: Install Pods
        run: pod install --repo-update
        working-directory: packages/mobile/ios

      - name: Build iOS
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: packages/mobile/ios/HomebaseFeed.xcodeproj
          workspace-path: packages/mobile/ios/HomebaseFeed.xcworkspace
          scheme: HomebaseFeed
          export-options: packages/mobile/ios/options.plist
          p12-base64: ${{ secrets.IOS_FEED_P12_BASE64 }}
          mobileprovision-base64: |
            ${{ secrets.FEED_IOS_MOBILE_PROVISION_BASE64 }}
            ${{ secrets.FEED_APP_GROUP_IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_FEED_CERTIFICATE_PASSWORD }}

      - name: Rename IPA
        run: mv output.ipa homebase-id-app.ipa

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: homebase-id-app.ipa

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: homebase-id-app.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
